vim.keymap.set("n", "pd", "<cmd>lua require('goto-preview').goto_preview_definition()<CR>", { noremap = true, desc = "Preview definition in floating window" })
vim.keymap.set("n", "pg", "<cmd>lua require('goto-preview').goto_preview_type_definition()<CR>", { noremap = true,  desc = "Preview type definition" })
vim.keymap.set("n", "pi", "<cmd>lua require('goto-preview').goto_preview_implementation()<CR>", { noremap = true,  desc = "Preview implementation" })
vim.keymap.set("n", "pD", "<cmd>lua require('goto-preview').goto_declaration()<CR>", { noremap = true,  desc = "Goto decleration" })
vim.keymap.set("n", "pr", "<cmd>lua require('goto-preview').goto_preview_references()<CR>", { noremap = true,  desc = "Go to references" })
vim.keymap.set("n", "cc", "<cmd>lua require('goto-preview').close_all_win()<CR>", { noremap = true,  desc = "Goto preview close all windows" })
