vim.keymap.set("n", "pd", "<cmd>lua require('goto-preview').goto_preview_definition()<CR>", { desc = "Preview definition in floating window" })
vim.keymap.set("n", "pg", "<cmd>lua require('goto-preview').goto_preview_type_definition()<CR>", { desc = "Preview type definition" })
vim.keymap.set("n", "pi", "<cmd>lua require('goto-preview').goto_preview_implementation()<CR>", { desc = "Preview implementation" })
vim.keymap.set("n", "pD", "<cmd>lua require('goto-preview').goto_declaration()<CR>", { desc = "Goto declaration" })
vim.keymap.set("n", "pr", "<cmd>lua require('goto-preview').goto_preview_references()<CR>", { desc = "Go to references" })
vim.keymap.set("n", "cc", "<cmd>lua require('goto-preview').close_all_win()<CR>", { desc = "Close preview windows" })
